version: 0.2

phases:
    install:
        commands:
          - echo ---Start Install Phase on `date`---
            #Update Packages
          - apt-get update
          - #Headless Chrome
          - echo Installing Chrome.......
          - apt-get install -y fonts-liberation libasound2 libnspr4 libnss3 libx11-xcb1 xdg-utils libxss1 libappindicator1 libindicator7
          - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          - dpkg -i google-chrome*.deb
          - echo ---End Install Phase on `date`---
        finally:
          - echo ---Start Install Finally on `date`---
          - echo ---End Install Finally on `date`---
    pre_build:
        commands:
          - echo ---Start Pre Build Phase on `date`---
          - npm install

          - echo Beginnning Linting
          - npm run lint
          - echo End Linting

        finally:
          - echo Start Pre Build Finally on `date`
          - echo End Pre Build Finally on `date`

    build:
        commands:
          - echo Start Build Phase on `date`
          - npm run dist

          - echo Beginning Unit Tests
          - npm run test:ci
          - echo End Unit Tests

          # - echo Begin E2E Tests
          # - npm run e2e
          # - echo End E2E Tests
          # - echo ---End Pre Build Phase on `date`---

          - echo End Build Phase on `date`

        finally:
          - echo Start Build Finally on `date`
          - echo End Build Finally on `date`

    post_build:
        commands:
          - echo ---Start Post Build Phase on `date`---

          - aws s3 sync ./dist/mclean-net s3://bigals-dev.com --acl 'public-read' --delete

          - echo ---End Post Build Pase on `date`---
        finally:
          - echo ---Start Post Build Finally on `date`---
          - echo ---End Post Build Finally on `date`---
